### ISSUE TITLE
Help wanted

### ISSUE THREAD

**Issue by rsyncOSX** [rsyncOSX/RsyncOSXicon#1]
The RsyncOSX icon is somewhat dull. I am not a graphic designer and If anyone can help to create a new icon for RsyncOSX would be great.

**Comment by grand-tastix** [comment]
Do you already have any mental picture along which lines the icon should look like?

**Comment by rsyncOSX** [comment]
I would like that the icon reflects that RsyncOSX is a kind of tool or a tool for backup. And maybe some kind of 3D effect. But still simple ... I am open for suggestions...

**Comment by forrestwalter** [comment]
I thought I'd offer this:

![rsyncosx icon 2](https://cloud.githubusercontent.com/assets/26230284/23636491/a6f57a5a-02a3-11e7-8371-f865117c50e2.png)

[rsyncosx.icns.zip](https://github.com/rsyncOSX/RsyncOSXicon/files/822965/rsyncosx.icns.zip)

**Comment by rsyncOSX** [comment]
This is really great, thx a lot. I am working on version 4, I will replace the old app icon with this..

**Comment by forrestwalter** [comment]
Great, glad you like it! :) Sure, "Forrest Walter" is fine. You might say "Icon by:" to distinguish between the app icon and the interface artwork.

**Comment by rsyncOSX** [comment]
Sure, will do.. I will release new version some sooner than planned du to new app icon..
